# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08e43076c245f84ff0249ba721305eec"
name = "greentee-spin-to-win"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_order_edits,write_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
